---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Verify ansible-pull service unit exists
      ansible.builtin.stat:
        path: /etc/systemd/system/ansible-pull.service
      register: ansible_pull_service_stat
      failed_when: not ansible_pull_service_stat.stat.exists

    - name: Verify ansible-pull timer unit exists
      ansible.builtin.stat:
        path: /etc/systemd/system/ansible-pull.timer
      register: ansible_pull_timer_stat
      failed_when: not ansible_pull_timer_stat.stat.exists

    - name: Verify timer is enabled
      ansible.builtin.systemd:
        name: ansible-pull.timer
      register: ansible_pull_timer_status
      failed_when: ansible_pull_timer_status.status.UnitFileState != "enabled"

    - name: Verify log directory exists
      ansible.builtin.stat:
        path: /var/log/ansible
      register: ansible_pull_logdir_stat
      failed_when: not ansible_pull_logdir_stat.stat.exists

    - name: Verify logrotate configuration exists
      ansible.builtin.stat:
        path: /etc/logrotate.d/ansible-pull
      register: ansible_pull_logrotate_stat
      failed_when: not ansible_pull_logrotate_stat.stat.exists

    - name: Verify working directory exists
      ansible.builtin.stat:
        path: /opt/iac-ansible
      register: ansible_pull_workdir_stat
      failed_when: not ansible_pull_workdir_stat.stat.exists
