---
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Apply sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true
