---
# =============================================================================
# IAC-Ansible Staging Inventory
# =============================================================================
# Usage: make deploy ENV=staging

all:
  vars:
    ansible_user: root
    ansible_python_interpreter: auto_silent

  children:
    # Asset Type Groups
    dev_test:
      hosts:
        0001-68.cloud.bauer-group.com:

    # Platform Groups
    debian:
      children:
        debian_13:
          hosts:
            0001-68.cloud.bauer-group.com:

    # Functional Groups
    auto_update:
      hosts:
        0001-68.cloud.bauer-group.com:
