---
galaxy_info:
  role_name: docker
  namespace: bauer_group
  author: BAUER GROUP
  description: Install and configure Docker CE with Compose plugin
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions: [jammy, noble, resolute]
    - name: Debian
      versions: [bookworm, trixie]
    - name: EL
      versions:
        - "all"

dependencies: []
